# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github_relate\local_storage\College_relative\Regression_analysis_calculator\UI_resources\Mwd.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1310, 900)
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(13)
        Mainwindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(490, 10, 591, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Trash_1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_1.setFont(font)
        self.Trash_1.setObjectName("Trash_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Trash_1)
        self.data_path = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_path.setFont(font)
        self.data_path.setObjectName("data_path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.data_path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_verify = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_verify.sizePolicy().hasHeightForWidth())
        self.path_verify.setSizePolicy(sizePolicy)
        self.path_verify.setObjectName("path_verify")
        self.horizontalLayout.addWidget(self.path_verify)
        self.path_input = QtWidgets.QPushButton(self.formLayoutWidget)
        self.path_input.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_input.sizePolicy().hasHeightForWidth())
        self.path_input.setSizePolicy(sizePolicy)
        self.path_input.setObjectName("path_input")
        self.horizontalLayout.addWidget(self.path_input)
        self.path_clear = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_clear.sizePolicy().hasHeightForWidth())
        self.path_clear.setSizePolicy(sizePolicy)
        self.path_clear.setObjectName("path_clear")
        self.horizontalLayout.addWidget(self.path_clear)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.Trash_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_2.setFont(font)
        self.Trash_2.setObjectName("Trash_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Trash_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modual_choose = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modual_choose.sizePolicy().hasHeightForWidth())
        self.modual_choose.setSizePolicy(sizePolicy)
        self.modual_choose.setObjectName("modual_choose")
        self.modual_choose.addItem("")
        self.modual_choose.addItem("")
        self.modual_choose.addItem("")
        self.modual_choose.addItem("")
        self.modual_choose.addItem("")
        self.horizontalLayout_2.addWidget(self.modual_choose)
        self.degree_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.degree_input.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.degree_input.sizePolicy().hasHeightForWidth())
        self.degree_input.setSizePolicy(sizePolicy)
        self.degree_input.setText("")
        self.degree_input.setObjectName("degree_input")
        self.horizontalLayout_2.addWidget(self.degree_input)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 350, 361, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Var_show = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Var_show.sizePolicy().hasHeightForWidth())
        self.Var_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Var_show.setFont(font)
        self.Var_show.setText("")
        self.Var_show.setObjectName("Var_show")
        self.gridLayout.addWidget(self.Var_show, 1, 1, 1, 1)
        self.Trash_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_4.sizePolicy().hasHeightForWidth())
        self.Trash_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_4.setFont(font)
        self.Trash_4.setObjectName("Trash_4")
        self.gridLayout.addWidget(self.Trash_4, 1, 0, 1, 1)
        self.Mean_show = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mean_show.sizePolicy().hasHeightForWidth())
        self.Mean_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Mean_show.setFont(font)
        self.Mean_show.setText("")
        self.Mean_show.setObjectName("Mean_show")
        self.gridLayout.addWidget(self.Mean_show, 2, 1, 1, 1)
        self.Trash_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_5.sizePolicy().hasHeightForWidth())
        self.Trash_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_5.setFont(font)
        self.Trash_5.setObjectName("Trash_5")
        self.gridLayout.addWidget(self.Trash_5, 2, 0, 1, 1)
        self.Trash_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_3.sizePolicy().hasHeightForWidth())
        self.Trash_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_3.setFont(font)
        self.Trash_3.setObjectName("Trash_3")
        self.gridLayout.addWidget(self.Trash_3, 3, 0, 1, 1)
        self.R_show = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_show.sizePolicy().hasHeightForWidth())
        self.R_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.R_show.setFont(font)
        self.R_show.setText("")
        self.R_show.setObjectName("R_show")
        self.gridLayout.addWidget(self.R_show, 3, 1, 1, 1)
        self.Trash_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_6.sizePolicy().hasHeightForWidth())
        self.Trash_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_6.setFont(font)
        self.Trash_6.setObjectName("Trash_6")
        self.gridLayout.addWidget(self.Trash_6, 4, 0, 1, 1)
        self.RSS_show = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RSS_show.sizePolicy().hasHeightForWidth())
        self.RSS_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.RSS_show.setFont(font)
        self.RSS_show.setText("")
        self.RSS_show.setObjectName("RSS_show")
        self.gridLayout.addWidget(self.RSS_show, 4, 1, 1, 1)
        self.Trash_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_7.sizePolicy().hasHeightForWidth())
        self.Trash_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_7.setFont(font)
        self.Trash_7.setObjectName("Trash_7")
        self.gridLayout.addWidget(self.Trash_7, 5, 0, 1, 1)
        self.sigma_show = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigma_show.sizePolicy().hasHeightForWidth())
        self.sigma_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sigma_show.setFont(font)
        self.sigma_show.setText("")
        self.sigma_show.setObjectName("sigma_show")
        self.gridLayout.addWidget(self.sigma_show, 5, 1, 1, 1)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(490, 130, 811, 761))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.figure_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.figure_layout.setContentsMargins(0, 0, 0, 0)
        self.figure_layout.setObjectName("figure_layout")
        self.btDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btDraw.setGeometry(QtCore.QRect(1090, 10, 91, 111))
        self.btDraw.setObjectName("btDraw")
        self.Trash_8 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_8.setGeometry(QtCore.QRect(10, 10, 101, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_8.sizePolicy().hasHeightForWidth())
        self.Trash_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_8.setFont(font)
        self.Trash_8.setObjectName("Trash_8")
        self.Trash_9 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_9.setGeometry(QtCore.QRect(10, 430, 101, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_9.sizePolicy().hasHeightForWidth())
        self.Trash_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_9.setFont(font)
        self.Trash_9.setObjectName("Trash_9")
        self.y_preview = QtWidgets.QTextEdit(self.centralwidget)
        self.y_preview.setEnabled(True)
        self.y_preview.setGeometry(QtCore.QRect(10, 480, 101, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.y_preview.setFont(font)
        self.y_preview.setObjectName("y_preview")
        self.x_preview = QtWidgets.QTextEdit(self.centralwidget)
        self.x_preview.setEnabled(True)
        self.x_preview.setGeometry(QtCore.QRect(10, 60, 101, 361))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.x_preview.setFont(font)
        self.x_preview.setObjectName("x_preview")
        self.Trash_10 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_10.setGeometry(QtCore.QRect(230, 190, 120, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_10.sizePolicy().hasHeightForWidth())
        self.Trash_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_10.setFont(font)
        self.Trash_10.setObjectName("Trash_10")
        self.coe_show = QtWidgets.QTextEdit(self.centralwidget)
        self.coe_show.setEnabled(False)
        self.coe_show.setGeometry(QtCore.QRect(120, 240, 361, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.coe_show.setFont(font)
        self.coe_show.setObjectName("coe_show")
        self.Trash_11 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_11.setGeometry(QtCore.QRect(230, 10, 120, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_11.sizePolicy().hasHeightForWidth())
        self.Trash_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_11.setFont(font)
        self.Trash_11.setObjectName("Trash_11")
        self.modual_preview = QtWidgets.QTextEdit(self.centralwidget)
        self.modual_preview.setEnabled(False)
        self.modual_preview.setGeometry(QtCore.QRect(120, 60, 361, 131))
        self.modual_preview.setObjectName("modual_preview")
        self.output_path = QtWidgets.QLineEdit(self.centralwidget)
        self.output_path.setGeometry(QtCore.QRect(120, 810, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_path.setFont(font)
        self.output_path.setObjectName("output_path")
        self.path_output = QtWidgets.QPushButton(self.centralwidget)
        self.path_output.setEnabled(False)
        self.path_output.setGeometry(QtCore.QRect(120, 860, 361, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_output.sizePolicy().hasHeightForWidth())
        self.path_output.setSizePolicy(sizePolicy)
        self.path_output.setObjectName("path_output")
        self.Trash_12 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_12.setGeometry(QtCore.QRect(120, 760, 361, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_12.sizePolicy().hasHeightForWidth())
        self.Trash_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_12.setFont(font)
        self.Trash_12.setObjectName("Trash_12")
        self.Trash_13 = QtWidgets.QLabel(self.centralwidget)
        self.Trash_13.setGeometry(QtCore.QRect(1190, 10, 111, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trash_13.sizePolicy().hasHeightForWidth())
        self.Trash_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Trash_13.setFont(font)
        self.Trash_13.setObjectName("Trash_13")
        self.png_name = QtWidgets.QLineEdit(self.centralwidget)
        self.png_name.setGeometry(QtCore.QRect(1190, 60, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.png_name.setFont(font)
        self.png_name.setObjectName("png_name")
        Mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "Regression_analysis"))
        self.Trash_1.setText(_translate("Mainwindow", "数据来源："))
        self.data_path.setPlaceholderText(_translate("Mainwindow", "输入导入数据的绝对路径,支持txt文件,默认同目录下的data.txt"))
        self.path_verify.setText(_translate("Mainwindow", "确定"))
        self.path_input.setText(_translate("Mainwindow", "确定导入"))
        self.path_clear.setText(_translate("Mainwindow", "清除"))
        self.Trash_2.setText(_translate("Mainwindow", "拟合模板："))
        self.modual_choose.setItemText(0, _translate("Mainwindow", "简单线性回归"))
        self.modual_choose.setItemText(1, _translate("Mainwindow", "多项式拟合"))
        self.modual_choose.setItemText(2, _translate("Mainwindow", "幂拟合"))
        self.modual_choose.setItemText(3, _translate("Mainwindow", "指数拟合"))
        self.modual_choose.setItemText(4, _translate("Mainwindow", "对数拟合"))
        self.degree_input.setPlaceholderText(_translate("Mainwindow", "输入degree"))
        self.Trash_4.setText(_translate("Mainwindow", "Var(y):"))
        self.Trash_5.setText(_translate("Mainwindow", "E(y):"))
        self.Trash_3.setText(_translate("Mainwindow", "R^2:"))
        self.Trash_6.setText(_translate("Mainwindow", "RSS:"))
        self.Trash_7.setText(_translate("Mainwindow", "LS(sigma^2):"))
        self.btDraw.setText(_translate("Mainwindow", "绘图"))
        self.Trash_8.setText(_translate("Mainwindow", "导入的x值"))
        self.Trash_9.setText(_translate("Mainwindow", "导入的y值"))
        self.y_preview.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Code\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7pt;\"><br /></p></body></html>"))
        self.Trash_10.setText(_translate("Mainwindow", "拟合后的参数::"))
        self.coe_show.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Code\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:400;\"><br /></p></body></html>"))
        self.Trash_11.setText(_translate("Mainwindow", "拟合模板预览:"))
        self.output_path.setPlaceholderText(_translate("Mainwindow", "默认同目录下的result.txt"))
        self.path_output.setText(_translate("Mainwindow", "确定导出"))
        self.Trash_12.setText(_translate("Mainwindow", "将上述参数导出,导出的绝对路径(后缀为txt):"))
        self.Trash_13.setText(_translate("Mainwindow", "保存为(.png)"))
        self.png_name.setPlaceholderText(_translate("Mainwindow", "默认为:数字.png"))

