---
title: "兰顿蚂蚁"
author: "管理学院 PB19020632 夏远林"
date: "主体完成时间 2021/12/13 文档完成时间 2021/12/13"
output: html_document
---
# 1.科学技术原理
<font size = 4>基于克里斯托夫·兰顿在1986年提出的兰顿蚂蚁框架实现  
具体为:  
在平面上的正方形格被填上黑色或白色。在其中一格正方形有一只“蚂蚁”。  
它的头部朝向上下左右其中一方。  
若蚂蚁在黑格，右转90度，将该格改为白格，向前移一步；  
若蚂蚁在白格，左转90度，将该格改为黑格，向前移一步。  
兰顿蚂蚁运行机理很简单，但是最后的结果会由于初始方向不同，边界条件不同(例如我这个可返回的边界)
蚂蚁数量不同，产生巨大的差异(比如在70x70的有返回的格点当中,不会出现无休止的重复图形,重复图形仅仅会出现很少的次数)  
这个机理存在于很多的事例当中  
例如带反射壁的markov chain  
例如非常返的连续时间markov chain
例如非齐次微分方程组的解  
等等……
</font>  

# 2.设计方案  
<font size =3>使用JavaFX库实现图形界面  
通过fxml接口将Scene Builder设计的场景与具体的Application进行关联,具体操作详见Main_ui类  

蚂蚁的移动格子通过Rectangle形成的二维数组实现,具体为Grid类,详情请打开相应文件查看  
蚂蚁的运动逻辑和蚂蚁的类的定义来自Ant类,详情请打开相应文档查看
动画的实现通过Timeline实现,详情见Main_ui类的具体方法,对应实例名称为"mainThread"  
剩余的方法和对象都已经进行详细的注释标注,参考具体文档即可</font>

# 3.创新性描述
<font size =4>
兰顿蚂蚁的思想是前人的,关于蚂蚁运动格子的设计也是参考了github上一些作者的思想  
但是具体的代码编写和实现全部是个人完成，并且<font color=red>时间线</font>的描述和建立也并没有参考任何人的文本  
蚂蚁的逻辑实现也全部是自己编写的</font>  

# 4.运行参数和运行结果
运行参数详见Config.java配置文件  
其中包括不仅限于：格子的规格，蚂蚁的默认初始位置，颜色等等.  
运行结果详见具体运行效果  

# 5.学习心得
<font color=blue size=4>程序类的学习很多全部靠自己摸索，没有那么多教程可以供参考  
就这个项目而言，我参考了bilibili上的javafx教程和javafx的官方文档，其中官方文档描述的非常详细  
但是因为过于详细，所以很难找到你想要的资料  
如果有条件的话，建议买个梯子去github上看或者去stackoverflow上寻找答案，国外的网站虽然存在阅读障碍，但是相比国内的网站资料，内容和准确性要丰富许多。  
</font>

# 参考资料
兰顿蚂蚁基础概念: https://zh.wikipedia.org/wiki/langton's%20ant  
github：https://github.com/search?q=Langton%27s+Ant  
stackoverflow：https://stackoverflow.com/search?q=javafx  
javafx官方文档：https://docs.oracle.com/javase/8/javafx/api/  



