# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\大三上计算机课程学习资料\面向对象编程\上机实验1\UI_resourses\AD_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ADWindow(object):
    def setupUi(self, ADWindow):
        ADWindow.setObjectName("ADWindow")
        ADWindow.setEnabled(True)
        ADWindow.resize(1200, 900)
        font = QtGui.QFont()
        font.setFamily("造字工房朗倩（非商用）常规体")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        ADWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ADWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titlelable = QtWidgets.QLabel(self.centralwidget)
        self.titlelable.setGeometry(QtCore.QRect(10, 5, 100, 30))
        self.titlelable.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelable.setObjectName("titlelable")
        self.BacktoMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.BacktoMainButton.setGeometry(QtCore.QRect(1000, 0, 200, 30))
        self.BacktoMainButton.setObjectName("BacktoMainButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 331, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Booksdata_input = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Booksdata_input.setContentsMargins(0, 0, 0, 0)
        self.Booksdata_input.setObjectName("Booksdata_input")
        self.title1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")
        self.Booksdata_input.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title1)
        self.trash1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.trash1.setObjectName("trash1")
        self.Booksdata_input.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.trash1)
        self.model_choose1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.model_choose1.setObjectName("model_choose1")
        self.model_choose1.addItem("")
        self.model_choose1.addItem("")
        self.model_choose1.addItem("")
        self.model_choose1.addItem("")
        self.Booksdata_input.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.model_choose1)
        self.bookID = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookID.setObjectName("bookID")
        self.Booksdata_input.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bookID)
        self.bookIDinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookIDinput.setToolTip("")
        self.bookIDinput.setMaxLength(14)
        self.bookIDinput.setObjectName("bookIDinput")
        self.Booksdata_input.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bookIDinput)
        self.bookName = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookName.setObjectName("bookName")
        self.Booksdata_input.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bookName)
        self.bookNameinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookNameinput.setEnabled(True)
        self.bookNameinput.setToolTip("")
        self.bookNameinput.setMaxLength(20)
        self.bookNameinput.setObjectName("bookNameinput")
        self.Booksdata_input.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bookNameinput)
        self.bookISBN = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookISBN.setObjectName("bookISBN")
        self.Booksdata_input.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bookISBN)
        self.bookISBNinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookISBNinput.setToolTip("")
        self.bookISBNinput.setMaxLength(13)
        self.bookISBNinput.setObjectName("bookISBNinput")
        self.Booksdata_input.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bookISBNinput)
        self.bookpublishing = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookpublishing.setObjectName("bookpublishing")
        self.Booksdata_input.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bookpublishing)
        self.bookpublishinginput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookpublishinginput.setMaxLength(20)
        self.bookpublishinginput.setObjectName("bookpublishinginput")
        self.Booksdata_input.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bookpublishinginput)
        self.bookpub_year = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookpub_year.setObjectName("bookpub_year")
        self.Booksdata_input.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bookpub_year)
        self.bookpub_yearinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookpub_yearinput.setMaxLength(7)
        self.bookpub_yearinput.setObjectName("bookpub_yearinput")
        self.Booksdata_input.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bookpub_yearinput)
        self.bookauthor = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookauthor.setObjectName("bookauthor")
        self.Booksdata_input.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bookauthor)
        self.bookauthorinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookauthorinput.setMaxLength(15)
        self.bookauthorinput.setObjectName("bookauthorinput")
        self.Booksdata_input.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bookauthorinput)
        self.booklabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.booklabel.setObjectName("booklabel")
        self.Booksdata_input.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.booklabel)
        self.booklabelinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.booklabelinput.setMaxLength(10)
        self.booklabelinput.setObjectName("booklabelinput")
        self.Booksdata_input.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.booklabelinput)
        self.bookuncheckout = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookuncheckout.setObjectName("bookuncheckout")
        self.Booksdata_input.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bookuncheckout)
        self.bookuncheckoutinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookuncheckoutinput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bookuncheckoutinput.setMaxLength(10)
        self.bookuncheckoutinput.setFrame(True)
        self.bookuncheckoutinput.setClearButtonEnabled(False)
        self.bookuncheckoutinput.setObjectName("bookuncheckoutinput")
        self.Booksdata_input.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bookuncheckoutinput)
        self.bookcheckout = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookcheckout.setObjectName("bookcheckout")
        self.Booksdata_input.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.bookcheckout)
        self.bookcheckoutinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookcheckoutinput.setMaxLength(10)
        self.bookcheckoutinput.setObjectName("bookcheckoutinput")
        self.Booksdata_input.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bookcheckoutinput)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.insert_1 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.insert_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(21)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_1.sizePolicy().hasHeightForWidth())
        self.insert_1.setSizePolicy(sizePolicy)
        self.insert_1.setObjectName("insert_1")
        self.horizontalLayout_5.addWidget(self.insert_1)
        self.modify_1 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.modify_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_1.sizePolicy().hasHeightForWidth())
        self.modify_1.setSizePolicy(sizePolicy)
        self.modify_1.setObjectName("modify_1")
        self.horizontalLayout_5.addWidget(self.modify_1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        self.checkBox_1.setMouseTracking(True)
        self.checkBox_1.setAcceptDrops(False)
        self.checkBox_1.setCheckable(True)
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setAutoRepeat(False)
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout_5.addWidget(self.checkBox_1)
        self.Booksdata_input.setLayout(12, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verifyButton_1 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verifyButton_1.sizePolicy().hasHeightForWidth())
        self.verifyButton_1.setSizePolicy(sizePolicy)
        self.verifyButton_1.setObjectName("verifyButton_1")
        self.horizontalLayout.addWidget(self.verifyButton_1)
        self.clearButton_1 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_1.sizePolicy().hasHeightForWidth())
        self.clearButton_1.setSizePolicy(sizePolicy)
        self.clearButton_1.setObjectName("clearButton_1")
        self.horizontalLayout.addWidget(self.clearButton_1)
        self.Booksdata_input.setLayout(11, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(360, 30, 831, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.book_insert_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.book_insert_label.setObjectName("book_insert_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.book_insert_label)
        self.booklist_insert = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.booklist_insert.setFont(font)
        self.booklist_insert.setToolTip("")
        self.booklist_insert.setMaxLength(10000)
        self.booklist_insert.setObjectName("booklist_insert")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.booklist_insert)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verifyButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verifyButton_2.sizePolicy().hasHeightForWidth())
        self.verifyButton_2.setSizePolicy(sizePolicy)
        self.verifyButton_2.setObjectName("verifyButton_2")
        self.horizontalLayout_2.addWidget(self.verifyButton_2)
        self.clearButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.clearButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_2.sizePolicy().hasHeightForWidth())
        self.clearButton_2.setSizePolicy(sizePolicy)
        self.clearButton_2.setObjectName("clearButton_2")
        self.horizontalLayout_2.addWidget(self.clearButton_2)
        self.PLinsert_1 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.PLinsert_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PLinsert_1.sizePolicy().hasHeightForWidth())
        self.PLinsert_1.setSizePolicy(sizePolicy)
        self.PLinsert_1.setObjectName("PLinsert_1")
        self.horizontalLayout_2.addWidget(self.PLinsert_1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(360, 100, 831, 71))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.reader_insert_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.reader_insert_label.setObjectName("reader_insert_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.reader_insert_label)
        self.readerlist_insert = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readerlist_insert.setFont(font)
        self.readerlist_insert.setToolTip("")
        self.readerlist_insert.setMaxLength(10000)
        self.readerlist_insert.setFrame(True)
        self.readerlist_insert.setObjectName("readerlist_insert")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.readerlist_insert)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verifyButton_3 = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verifyButton_3.sizePolicy().hasHeightForWidth())
        self.verifyButton_3.setSizePolicy(sizePolicy)
        self.verifyButton_3.setObjectName("verifyButton_3")
        self.horizontalLayout_3.addWidget(self.verifyButton_3)
        self.clearButton_3 = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.clearButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_3.sizePolicy().hasHeightForWidth())
        self.clearButton_3.setSizePolicy(sizePolicy)
        self.clearButton_3.setObjectName("clearButton_3")
        self.horizontalLayout_3.addWidget(self.clearButton_3)
        self.PLinsert_2 = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.PLinsert_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PLinsert_2.sizePolicy().hasHeightForWidth())
        self.PLinsert_2.setSizePolicy(sizePolicy)
        self.PLinsert_2.setObjectName("PLinsert_2")
        self.horizontalLayout_3.addWidget(self.PLinsert_2)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 170, 831, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textshow = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.textshow.setAlignment(QtCore.Qt.AlignCenter)
        self.textshow.setObjectName("textshow")
        self.verticalLayout.addWidget(self.textshow)
        self.mess_show = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(11)
        self.mess_show.setFont(font)
        self.mess_show.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.mess_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.mess_show.setObjectName("mess_show")
        self.verticalLayout.addWidget(self.mess_show)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 500, 331, 281))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.Booksdata_input_2 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.Booksdata_input_2.setContentsMargins(0, 0, 0, 0)
        self.Booksdata_input_2.setObjectName("Booksdata_input_2")
        self.trash2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.trash2.setObjectName("trash2")
        self.Booksdata_input_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.trash2)
        self.model_choose2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.model_choose2.setObjectName("model_choose2")
        self.model_choose2.addItem("")
        self.model_choose2.addItem("")
        self.model_choose2.addItem("")
        self.model_choose2.addItem("")
        self.Booksdata_input_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.model_choose2)
        self.readerID = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.readerID.setObjectName("readerID")
        self.Booksdata_input_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.readerID)
        self.readerIDinput = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.readerIDinput.setToolTip("")
        self.readerIDinput.setMaxLength(14)
        self.readerIDinput.setObjectName("readerIDinput")
        self.Booksdata_input_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.readerIDinput)
        self.readerName = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.readerName.setObjectName("readerName")
        self.Booksdata_input_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.readerName)
        self.readerNameinput = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.readerNameinput.setEnabled(True)
        self.readerNameinput.setToolTip("")
        self.readerNameinput.setMaxLength(5)
        self.readerNameinput.setObjectName("readerNameinput")
        self.Booksdata_input_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.readerNameinput)
        self.reader_type = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.reader_type.setObjectName("reader_type")
        self.Booksdata_input_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.reader_type)
        self.reader_typeinput = QtWidgets.QComboBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reader_typeinput.setFont(font)
        self.reader_typeinput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reader_typeinput.setDuplicatesEnabled(False)
        self.reader_typeinput.setFrame(True)
        self.reader_typeinput.setObjectName("reader_typeinput")
        self.reader_typeinput.addItem("")
        self.reader_typeinput.addItem("")
        self.Booksdata_input_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.reader_typeinput)
        self.phone = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.phone.setObjectName("phone")
        self.Booksdata_input_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.phoneinput = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.phoneinput.setToolTip("")
        self.phoneinput.setMaxLength(11)
        self.phoneinput.setObjectName("phoneinput")
        self.Booksdata_input_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.phoneinput)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verifyButton_4 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verifyButton_4.sizePolicy().hasHeightForWidth())
        self.verifyButton_4.setSizePolicy(sizePolicy)
        self.verifyButton_4.setObjectName("verifyButton_4")
        self.horizontalLayout_4.addWidget(self.verifyButton_4)
        self.clearButton_4 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_4.sizePolicy().hasHeightForWidth())
        self.clearButton_4.setSizePolicy(sizePolicy)
        self.clearButton_4.setObjectName("clearButton_4")
        self.horizontalLayout_4.addWidget(self.clearButton_4)
        self.Booksdata_input_2.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.title2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.title2.setAlignment(QtCore.Qt.AlignCenter)
        self.title2.setObjectName("title2")
        self.Booksdata_input_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.insert_2 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.insert_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(21)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_2.sizePolicy().hasHeightForWidth())
        self.insert_2.setSizePolicy(sizePolicy)
        self.insert_2.setObjectName("insert_2")
        self.horizontalLayout_6.addWidget(self.insert_2)
        self.modify_2 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.modify_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_2.sizePolicy().hasHeightForWidth())
        self.modify_2.setSizePolicy(sizePolicy)
        self.modify_2.setObjectName("modify_2")
        self.horizontalLayout_6.addWidget(self.modify_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMouseTracking(True)
        self.checkBox_2.setAcceptDrops(False)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setAutoRepeat(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        self.Booksdata_input_2.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 790, 331, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.totalbooks_show = QtWidgets.QPushButton(self.layoutWidget)
        self.totalbooks_show.setObjectName("totalbooks_show")
        self.horizontalLayout_7.addWidget(self.totalbooks_show)
        self.totalreaders_show = QtWidgets.QPushButton(self.layoutWidget)
        self.totalreaders_show.setObjectName("totalreaders_show")
        self.horizontalLayout_7.addWidget(self.totalreaders_show)
        ADWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ADWindow)
        QtCore.QMetaObject.connectSlotsByName(ADWindow)

    def retranslateUi(self, ADWindow):
        _translate = QtCore.QCoreApplication.translate
        ADWindow.setWindowTitle(_translate("ADWindow", "管理员窗口"))
        self.titlelable.setToolTip(_translate("ADWindow", "这是管理员菜单"))
        self.titlelable.setText(_translate("ADWindow", "管理员菜单"))
        self.BacktoMainButton.setText(_translate("ADWindow", "返回用户选择界面"))
        self.title1.setText(_translate("ADWindow", "单个图书信息导入/编辑/删除"))
        self.trash1.setText(_translate("ADWindow", "模式选择:"))
        self.model_choose1.setItemText(0, _translate("ADWindow", "导入"))
        self.model_choose1.setItemText(1, _translate("ADWindow", "编辑"))
        self.model_choose1.setItemText(2, _translate("ADWindow", "搜索"))
        self.model_choose1.setItemText(3, _translate("ADWindow", "删除"))
        self.bookID.setText(_translate("ADWindow", "ID:       "))
        self.bookIDinput.setPlaceholderText(_translate("ADWindow", "书的ID"))
        self.bookName.setText(_translate("ADWindow", "Name:"))
        self.bookNameinput.setPlaceholderText(_translate("ADWindow", "书名"))
        self.bookISBN.setText(_translate("ADWindow", "ISBN:"))
        self.bookISBNinput.setPlaceholderText(_translate("ADWindow", "国家标准书号(13位数字)"))
        self.bookpublishing.setText(_translate("ADWindow", "出版社:"))
        self.bookpublishinginput.setToolTip(_translate("ADWindow", "书名"))
        self.bookpublishinginput.setPlaceholderText(_translate("ADWindow", "出版社"))
        self.bookpub_year.setText(_translate("ADWindow", "出版年月:"))
        self.bookpub_yearinput.setToolTip(_translate("ADWindow", "书名"))
        self.bookpub_yearinput.setPlaceholderText(_translate("ADWindow", "出版年月"))
        self.bookauthor.setText(_translate("ADWindow", "作者:"))
        self.bookauthorinput.setToolTip(_translate("ADWindow", "作者"))
        self.bookauthorinput.setPlaceholderText(_translate("ADWindow", "作者/author"))
        self.booklabel.setText(_translate("ADWindow", "标签:"))
        self.booklabelinput.setToolTip(_translate("ADWindow", "书名"))
        self.booklabelinput.setPlaceholderText(_translate("ADWindow", "如：四大名著/世界经典名著等"))
        self.bookuncheckout.setText(_translate("ADWindow", "在库数量:"))
        self.bookuncheckoutinput.setToolTip(_translate("ADWindow", "只能输入0-10000的整形数字"))
        self.bookuncheckoutinput.setPlaceholderText(_translate("ADWindow", "在库数量"))
        self.bookcheckout.setText(_translate("ADWindow", "借出数量:"))
        self.bookcheckoutinput.setToolTip(_translate("ADWindow", "只能输入0-10000的整形数字"))
        self.bookcheckoutinput.setPlaceholderText(_translate("ADWindow", "借出数量"))
        self.insert_1.setText(_translate("ADWindow", "完成导入"))
        self.modify_1.setText(_translate("ADWindow", "修改/删除"))
        self.checkBox_1.setToolTip(_translate("ADWindow", "是否锁定搜索到的信息"))
        self.checkBox_1.setText(_translate("ADWindow", "锁定"))
        self.verifyButton_1.setText(_translate("ADWindow", "确定(在右侧预览)"))
        self.clearButton_1.setText(_translate("ADWindow", "清除输入"))
        self.book_insert_label.setText(_translate("ADWindow", "批量导入图书的绝对路径:"))
        self.booklist_insert.setPlaceholderText(_translate("ADWindow", "绝对路径(请在相应文件的属性中查看,并且记得将\"\\\"替换为\"/\")"))
        self.verifyButton_2.setText(_translate("ADWindow", "确定"))
        self.clearButton_2.setText(_translate("ADWindow", "清除"))
        self.PLinsert_1.setText(_translate("ADWindow", "确定导入"))
        self.reader_insert_label.setText(_translate("ADWindow", "批量导入读者的绝对路径:"))
        self.readerlist_insert.setPlaceholderText(_translate("ADWindow", "绝对路径(请在相应文件的属性中查看,并且记得将\"\\\"替换为\"/\")"))
        self.verifyButton_3.setText(_translate("ADWindow", "确定"))
        self.clearButton_3.setText(_translate("ADWindow", "清除"))
        self.PLinsert_2.setText(_translate("ADWindow", "确定导入"))
        self.textshow.setText(_translate("ADWindow", "内容显示:"))
        self.mess_show.setHtml(_translate("ADWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Code\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Fira Code Retina\';\"><br /></p></body></html>"))
        self.trash2.setText(_translate("ADWindow", "模式选择:"))
        self.model_choose2.setItemText(0, _translate("ADWindow", "导入"))
        self.model_choose2.setItemText(1, _translate("ADWindow", "编辑"))
        self.model_choose2.setItemText(2, _translate("ADWindow", "搜索"))
        self.model_choose2.setItemText(3, _translate("ADWindow", "删除"))
        self.readerID.setText(_translate("ADWindow", "ID:       "))
        self.readerIDinput.setPlaceholderText(_translate("ADWindow", "读者ID"))
        self.readerName.setText(_translate("ADWindow", "Name:"))
        self.readerNameinput.setPlaceholderText(_translate("ADWindow", "读者中文姓名(最大支持5个字)"))
        self.reader_type.setText(_translate("ADWindow", "类型:"))
        self.reader_typeinput.setItemText(0, _translate("ADWindow", "普通"))
        self.reader_typeinput.setItemText(1, _translate("ADWindow", "贵宾"))
        self.phone.setText(_translate("ADWindow", "电话:"))
        self.phoneinput.setPlaceholderText(_translate("ADWindow", "读者电话(11位数字)"))
        self.verifyButton_4.setText(_translate("ADWindow", "确定(在右侧预览)"))
        self.clearButton_4.setText(_translate("ADWindow", "清除输入"))
        self.title2.setText(_translate("ADWindow", "单个读者信息导入/编辑/删除"))
        self.insert_2.setText(_translate("ADWindow", "完成导入"))
        self.modify_2.setText(_translate("ADWindow", "修改/删除"))
        self.checkBox_2.setToolTip(_translate("ADWindow", "是否锁定搜索到的信息"))
        self.checkBox_2.setText(_translate("ADWindow", "锁定"))
        self.totalbooks_show.setToolTip(_translate("ADWindow", "在右侧的内容显示中显示所有书籍的信息"))
        self.totalbooks_show.setText(_translate("ADWindow", "所有书籍数据查看"))
        self.totalreaders_show.setToolTip(_translate("ADWindow", "在右侧的内容显示中显示所有的读者信息"))
        self.totalreaders_show.setText(_translate("ADWindow", "所有读者数据查看"))

