# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\大三上计算机课程学习资料\面向对象编程\上机实验1\UI_resourses\RD_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RDWindow(object):
    def setupUi(self, RDWindow):
        RDWindow.setObjectName("RDWindow")
        RDWindow.resize(1200, 900)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setUnderline(False)
        RDWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(RDWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titlelabel = QtWidgets.QLabel(self.centralwidget)
        self.titlelabel.setGeometry(QtCore.QRect(10, 5, 100, 30))
        self.titlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelabel.setObjectName("titlelabel")
        self.BacktoMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.BacktoMainButton.setGeometry(QtCore.QRect(990, 5, 200, 30))
        self.BacktoMainButton.setObjectName("BacktoMainButton")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 330, 331, 131))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.readers_data = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.readers_data.setContentsMargins(0, 0, 0, 0)
        self.readers_data.setObjectName("readers_data")
        self.title2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.title2.setAlignment(QtCore.Qt.AlignCenter)
        self.title2.setObjectName("title2")
        self.readers_data.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title2)
        self.readerName = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.readerName.setObjectName("readerName")
        self.readers_data.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.readerName)
        self.readerNameinput = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.readerNameinput.setEnabled(True)
        self.readerNameinput.setToolTip("")
        self.readerNameinput.setMaxLength(5)
        self.readerNameinput.setObjectName("readerNameinput")
        self.readers_data.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.readerNameinput)
        self.phone = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.phone.setObjectName("phone")
        self.readers_data.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.phoneinput = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.phoneinput.setToolTip("")
        self.phoneinput.setMaxLength(11)
        self.phoneinput.setObjectName("phoneinput")
        self.readers_data.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phoneinput)
        self.clearButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_2.sizePolicy().hasHeightForWidth())
        self.clearButton_2.setSizePolicy(sizePolicy)
        self.clearButton_2.setObjectName("clearButton_2")
        self.readers_data.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.clearButton_2)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 40, 331, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.books_data = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.books_data.setContentsMargins(0, 0, 0, 0)
        self.books_data.setObjectName("books_data")
        self.title1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")
        self.books_data.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title1)
        self.bookName = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookName.setObjectName("bookName")
        self.books_data.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bookName)
        self.bookNameinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookNameinput.setEnabled(True)
        self.bookNameinput.setToolTip("")
        self.bookNameinput.setMaxLength(20)
        self.bookNameinput.setObjectName("bookNameinput")
        self.books_data.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bookNameinput)
        self.bookISBN = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookISBN.setObjectName("bookISBN")
        self.books_data.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bookISBN)
        self.bookISBNinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookISBNinput.setToolTip("")
        self.bookISBNinput.setMaxLength(13)
        self.bookISBNinput.setObjectName("bookISBNinput")
        self.books_data.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bookISBNinput)
        self.bookpublishing = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookpublishing.setObjectName("bookpublishing")
        self.books_data.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bookpublishing)
        self.bookpublishinginput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookpublishinginput.setMaxLength(20)
        self.bookpublishinginput.setObjectName("bookpublishinginput")
        self.books_data.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bookpublishinginput)
        self.bookpub_year = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookpub_year.setObjectName("bookpub_year")
        self.books_data.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bookpub_year)
        self.bookpub_yearinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookpub_yearinput.setMaxLength(7)
        self.bookpub_yearinput.setObjectName("bookpub_yearinput")
        self.books_data.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bookpub_yearinput)
        self.bookauthor = QtWidgets.QLabel(self.formLayoutWidget)
        self.bookauthor.setObjectName("bookauthor")
        self.books_data.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bookauthor)
        self.bookauthorinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bookauthorinput.setMaxLength(15)
        self.bookauthorinput.setObjectName("bookauthorinput")
        self.books_data.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bookauthorinput)
        self.booklabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.booklabel.setObjectName("booklabel")
        self.books_data.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.booklabel)
        self.booklabelinput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.booklabelinput.setMaxLength(10)
        self.booklabelinput.setObjectName("booklabelinput")
        self.books_data.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.booklabelinput)
        self.clearButton_1 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton_1.sizePolicy().hasHeightForWidth())
        self.clearButton_1.setSizePolicy(sizePolicy)
        self.clearButton_1.setObjectName("clearButton_1")
        self.books_data.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.clearButton_1)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(370, 20, 91, 21))
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setIndent(-1)
        self.label1.setObjectName("label1")
        self.books_inf_show = QtWidgets.QTextEdit(self.centralwidget)
        self.books_inf_show.setGeometry(QtCore.QRect(380, 40, 711, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.books_inf_show.setFont(font)
        self.books_inf_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.books_inf_show.setReadOnly(True)
        self.books_inf_show.setObjectName("books_inf_show")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(370, 310, 91, 21))
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setIndent(-1)
        self.label2.setObjectName("label2")
        self.readers_inf_show = QtWidgets.QTextEdit(self.centralwidget)
        self.readers_inf_show.setGeometry(QtCore.QRect(380, 330, 711, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.readers_inf_show.setFont(font)
        self.readers_inf_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.readers_inf_show.setReadOnly(True)
        self.readers_inf_show.setObjectName("readers_inf_show")
        self.borrowed_books_show = QtWidgets.QTextEdit(self.centralwidget)
        self.borrowed_books_show.setGeometry(QtCore.QRect(40, 490, 331, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.borrowed_books_show.setFont(font)
        self.borrowed_books_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.borrowed_books_show.setReadOnly(True)
        self.borrowed_books_show.setObjectName("borrowed_books_show")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(30, 470, 91, 21))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setIndent(-1)
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(370, 470, 91, 21))
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setIndent(-1)
        self.label4.setObjectName("label4")
        self.borrow_history_show = QtWidgets.QTextEdit(self.centralwidget)
        self.borrow_history_show.setGeometry(QtCore.QRect(380, 490, 711, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.borrow_history_show.setFont(font)
        self.borrow_history_show.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.borrow_history_show.setReadOnly(True)
        self.borrow_history_show.setObjectName("borrow_history_show")
        self.returnBT = QtWidgets.QPushButton(self.centralwidget)
        self.returnBT.setEnabled(False)
        self.returnBT.setGeometry(QtCore.QRect(40, 810, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.returnBT.setFont(font)
        self.returnBT.setObjectName("returnBT")
        self.borrowBT = QtWidgets.QPushButton(self.centralwidget)
        self.borrowBT.setEnabled(False)
        self.borrowBT.setGeometry(QtCore.QRect(1100, 40, 75, 261))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.borrowBT.setFont(font)
        self.borrowBT.setObjectName("borrowBT")
        RDWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RDWindow)
        QtCore.QMetaObject.connectSlotsByName(RDWindow)

    def retranslateUi(self, RDWindow):
        _translate = QtCore.QCoreApplication.translate
        RDWindow.setWindowTitle(_translate("RDWindow", "读者窗口"))
        self.titlelabel.setToolTip(_translate("RDWindow", "这是管理员菜单"))
        self.titlelabel.setText(_translate("RDWindow", "读者菜单"))
        self.BacktoMainButton.setText(_translate("RDWindow", "返回用户选择界面"))
        self.title2.setText(_translate("RDWindow", "读者信息查询"))
        self.readerName.setText(_translate("RDWindow", "Name:"))
        self.readerNameinput.setPlaceholderText(_translate("RDWindow", "读者中文姓名(最大支持5个字)"))
        self.phone.setText(_translate("RDWindow", "电话:    "))
        self.phoneinput.setPlaceholderText(_translate("RDWindow", "读者电话(11位数字)"))
        self.clearButton_2.setText(_translate("RDWindow", "清除输入"))
        self.title1.setText(_translate("RDWindow", "图书信息查询"))
        self.bookName.setText(_translate("RDWindow", "书名:"))
        self.bookNameinput.setPlaceholderText(_translate("RDWindow", "书名"))
        self.bookISBN.setText(_translate("RDWindow", "ISBN:"))
        self.bookISBNinput.setPlaceholderText(_translate("RDWindow", "国家标准书号(13位数字)"))
        self.bookpublishing.setText(_translate("RDWindow", "出版社:"))
        self.bookpublishinginput.setToolTip(_translate("RDWindow", "书名"))
        self.bookpublishinginput.setPlaceholderText(_translate("RDWindow", "出版社"))
        self.bookpub_year.setText(_translate("RDWindow", "出版年月:"))
        self.bookpub_yearinput.setToolTip(_translate("RDWindow", "书名"))
        self.bookpub_yearinput.setPlaceholderText(_translate("RDWindow", "出版年月"))
        self.bookauthor.setText(_translate("RDWindow", "作者:"))
        self.bookauthorinput.setToolTip(_translate("RDWindow", "作者"))
        self.bookauthorinput.setPlaceholderText(_translate("RDWindow", "作者/author"))
        self.booklabel.setText(_translate("RDWindow", "标签:"))
        self.booklabelinput.setToolTip(_translate("RDWindow", "书名"))
        self.booklabelinput.setPlaceholderText(_translate("RDWindow", "如：四大名著/世界经典名著等"))
        self.clearButton_1.setText(_translate("RDWindow", "清除输入"))
        self.label1.setText(_translate("RDWindow", "图书信息:"))
        self.label2.setText(_translate("RDWindow", "读者信息:"))
        self.label3.setText(_translate("RDWindow", "在借图书:"))
        self.label4.setText(_translate("RDWindow", "借阅历史:"))
        self.returnBT.setText(_translate("RDWindow", "归还"))
        self.borrowBT.setText(_translate("RDWindow", "借出"))

